mvcCentroMedicoV2/mvcCentroMedicoV2/Controllers/ReservaController.cs
using Buss;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Controllers
{
    public class ReservaController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            // Mis reservas

            int id = int.Parse(Session["idusuario"].ToString());

            List<MisReservasModel> lista = BussReserva.MisReservas(id);
            return View(lista);
        }

        [HttpGet]
        public ActionResult HorasDisponibles()
        {
            // Horas disponibles
            List<HorasDisponiblesModel> lista = BussReserva.HorasDisponibles();
            return View(lista);
        }

        [HttpPost]
        public ActionResult HorasDisponibles(FormCollection frm)
        {
            // Horas disponibles
            List<HorasDisponiblesModel> lista = BussReserva.HorasDisponibles();
            return View(lista);
        }

        [HttpGet]
        public ActionResult TomarHora(int id)
        {
            HoraModel obj = BussHora.Buscar(id);
            return View(obj);
        }

        [HttpPost]
        public ActionResult TomarHora(int id, FormCollection frm)
        {
            int idpac = int.Parse(Session["idusuario"].ToString());

            ReservaModel obj = new ReservaModel();
            obj.Medico = new MedicoModel();
            obj.Medico.Idmedico = int.Parse(frm["idmedico"].ToString());
            obj.Paciente = new PacienteModel();
            obj.Paciente.Idpaciente = idpac;
            obj.Hora = new HoraModel();
            obj.Hora.Idhora = int.Parse(frm["idhora"].ToString());

            BussReserva.TomarHora(obj);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AnularReserva(int id)
        {
            MisReservasModel obj = BussReserva.Buscar(id);
            return View(obj);
        }

        [HttpPost]
        public ActionResult AnularReserva(int id, FormCollection frm)
        {
            BussReserva.AnularReserva(id);
            return RedirectToAction("Index");
        }
    }
}

mvcCentroMedicoV2/mvcCentroMedicoV2/Views/Shared/_Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/_web/css/bootstrap.css" rel="stylesheet" />
    <link href="~/_web/css/base.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>@ViewBag.TitlePag</h2>
            </div>
            <div class="card-body divLogin">
                <!--
                    En RenderBody se visualiza el contenido de
                    todas las vistas que utilicen esta plantilla
                -->
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

mvcCentroMedicoV2/mvcCentroMedicoV2/Views/Shared/_Plantilla.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/_web/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>@ViewBag.TitlePag</h2>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-2">
                        @Html.ActionLink("Mis reservas", "Index", "Reserva")
                    </div>
                    <div class="col-md-2">
                        @Html.ActionLink("Horas disponibles", "HorasDisponibles", "Reserva")
                    </div>
                </div>
                <hr />
                <!--
                    En RenderBody se visualiza el contenido de
                    todas las vistas que utilicen esta plantilla
                -->
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>